# Generated by Django 5.2.1 on 2025-06-02 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0002_pdfupload_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfimage',
            name='pdf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pdfapp.pdfupload'),
            preserve_default=False,
        ),
    ]
