# Generated by Django 5.2.1 on 2025-06-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='download_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='free_uses',
            field=models.IntegerField(default=5),
        ),
    ]
