# Generated by Django 5.2.1 on 2025-06-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0005_remove_userprofile_download_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='free_uses',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
