# Generated by Django 5.2.1 on 2025-06-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0007_alter_userprofile_user_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
