# Generated by Django 5.2.1 on 2025-06-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0008_userprofile_paid_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_downloads',
        ),
    ]
