# Generated by Django 5.2.1 on 2025-06-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfapp', '0009_remove_userprofile_paid_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_downloads',
            field=models.BooleanField(default=False),
        ),
    ]
